version: '3.8'
services: 
  python:
    build:
      context: .
      dockerfile: Dockerfile.python
    volumes:
      -  ./backend:/anagram
  react:
    build:
      context: .
      dockerfile: Dockerfile.react
    ports:
    - "3000:3000"
    stdin_open: true
    volumes:
      - .:/anagram